# Generated by Django 3.2.20 on 2023-08-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_feedback_musictrack_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='MusicTrack',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
