# Generated by Django 3.2.20 on 2023-08-11 15:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.RemoveField(
            model_name='track',
            name='image',
        ),
        migrations.RemoveField(
            model_name='track',
            name='music_file',
        ),
        migrations.RemoveField(
            model_name='track',
            name='profile',
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
    ]
