# Generated by Django 3.2.20 on 2023-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_auto_20230811_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file_url',
            field=models.URLField(default='https://example.com/default/path/to/file'),
        ),
    ]
