# Generated by Django 3.2.20 on 2023-08-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_alter_track_audio_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='use_in_sets',
            field=models.BooleanField(default=False),
        ),
    ]
