# Generated by Django 3.2.20 on 2023-08-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_feedback_use_in_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='use_in_sets',
        ),
    ]
