# Generated by Django 3.2.20 on 2023-08-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_auto_20230810_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='genre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genre',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
