# Generated by Django 3.2.20 on 2023-08-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_feedback_listened_to_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
