# Generated by Django 3.2.20 on 2023-08-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0005_auto_20230810_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
